<?php
    $vb = $this->viewBag;
    $obj = $vb->obj;
    $out = $obj->getError();
    $status = ['Gebruiker', 'Beheerder', 'Eigenaar', 'Leraar'];

    if ($obj->_isAdmin) 
    {
        $aUsers = [];
        $out = "";
?>
<h2 class="center">Beheer</h2>
<hr>
<form method='post'>
    <div class='userContainer'>
        <div class="btnsActions">
            <input class="a-button a-delete" type="button" onclick="" value="Verwijderen">
            <br>
            <br>
                status naar:
            <br>
            <input class="a-button a-action" type="submit" name="btnPromoteAcc" value="Beheerder">
            <br><br>
            <input class="a-button a-action" type="submit" name="btnDemoteAcc" value="Gebruiker">  
            <br><br>
            <input class="a-button a-action" type="submit" name="btnPromoteTeacher" value="Leraar">
            <br><br>
            <p><?= $obj->_Message; ?></p>      
        </div>
        <div class="userTable centerdiv">
            <table class='viewTable <?= $vb->cssClass ?>'>
                <tr>
                    <th></th>
                    <th><b>Naam</b></th>
                    <th><b>Gebruikersnaam</b></th>
                    <th><b>E-Mail</b></th>
                    <th><b>Status</b></th>
                </tr>
                <!-- tabel users -->
                <?php
                foreach ($obj->users as $user)
                {                
                    ?>
                    <tr>
                        <td><center><input type="radio" name="rbtnAction" value="<?= $user['id']; ?>"></center></td>
                        <td><?= "{$user['name']} {$user['tv']} {$user['Lastname']}"; ?></td>
                        <td><?= $user['username'] ; ?></td>
                        <td><?= $user['email'] ?></td>                       
                        <td><?= $status[$user['rights']] ?></td>
                    </tr>
                    <?php
                }
                ?>
            </table>
        </div> 
    </div>                    
</form>
<?php
    }
    echo $out;