<?php
if ( isset($_SESSION['login']) && $_SESSION['login'] == true)
{ 
    $obj = $this->viewBag->obj;
?>
<div class="centerdiv">
	<form method="post">

		<table class="viewTable <?= $this->viewBag->cssClass ?>">
			<tr>
				<th colspan="2">Wachtwoord wijzigen</th>
			</tr>
			<tr>
				<td>Huidige wachtwoord:</td>
				<td><input type="password" name="oldPassword"></td>
			</tr>
			<tr>
				<td>Nieuwe wachtwoord:</td>
				<td><input type="password" name="newPassword"></td>
			</tr>
			<tr>
				<td>Opnieuw het nieuwe wachtwoord:</td>
				<td><input type="password" name="checkPassword"></td>
			</tr>
			<tr>
				<td colspan="2"><input type="submit" name="btnChange" value="Wijzig"></td>
			</tr>
		</table>

		<?= $obj->_out ?>
	
	</form>
</div>  
<?php
}

?>